# action.yml
name: 'Docker Shell Action'
description: 'Greet someone and record the time'
inputs:
  some-file-path:
    description: Path to text file we need from previous step.
    required: true
    default: './dummy.txt'
  sample-string:
    description: String input
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    # NOTE: Order is important here. This order must match the order and 
    # number of the args defined in the CLI_ARG literal in main.py
    - ${{ inputs.some-file-path }}
    - ${{ inputs.sample-string }}