name: Example Usage

on: push

env:
  DATA_FILE_PATH: ./step-one-output.txt

jobs:
  action-based-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create data file
        run: echo "HELLO" > "${{ env.DATA_FILE_PATH }}"
      
      - name: Use DSA Action
        uses: ./
        with:
          some-file-path: "${{ env.DATA_FILE_PATH }}"
          sample-string: "matt-wiley-test"
      